server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/djl394922860/interview-preparation.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - config
          username: djl394922860
          password: djl394922860=
          default-label: master
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
